"""add auth user id to users

Revision ID: 34c232ba0244
Revises: 0315aa578a33
Create Date: 2026-10-04 17:13:28.161592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c232ba0244'
down_revision: Union[str, Sequence[str], None] = '0315aa578a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_user_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint("uq_user_auth_user_id", 'users', ['auth_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("uq_user_auth_user_id", 'users', type_='unique')
    op.drop_column('users', 'auth_user_id')
    # ### end Alembic commands ###
