"""add businesses table

Revision ID: ff6926dc7c60
Revises: a25455ed51f4
Create Date: 2026-09-30 11:43:39.905650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6926dc7c60'
down_revision: Union[str, Sequence[str], None] = 'a25455ed51f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    #Trigger
    op.execute("""
    CREATE OR REPLACE FUNCTION set_business_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = CURRENT_TIMESTAMP;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER business_updated_at_trigger
    BEFORE UPDATE ON businesses
    FOR EACH ROW
    EXECUTE FUNCTION set_business_updated_at();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TRIGGER IF EXISTS business_updated_at_trigger ON businesses;""")
    op.execute("""DROP FUNCTION IF EXISTS set_business_updated_at();""")
    op.drop_table('businesses')
    # ### end Alembic commands ###